import { createContext, useContext, useEffect, useState, type FormEvent, type ReactNode } from "react";
import { motion, useReducedMotion } from "motion/react";
import {
  AlertTriangle, ArrowLeft, ArrowRight, Bell, BrainCircuit, CalendarDays, Check,
  ChevronRight, ClipboardCheck, FileText, LayoutDashboard, Lightbulb, ListChecks,
  Menu, MessageSquareText, Search, Sparkles, Target, Users, X,
} from "lucide-react";
import { toast } from "sonner";
import creatyLogo from "@/assets/creaty-logo.png";
import { supabase } from "@/integrations/supabase/client";

const WaitlistContext = createContext<{ open: () => void }>({ open: () => undefined });

function Section({ id, light = false, children, className = "" }: { id?: string; light?: boolean; children: ReactNode; className?: string }) {
  return <section id={id} className={`${light ? "bg-creaty-cream text-creaty-black" : "bg-creaty-black text-creaty-cream"} relative w-full px-5 py-20 md:px-10 md:py-28 lg:px-16 ${className}`}><div className="mx-auto max-w-7xl">{children}</div></section>;
}

function CTAButton({ children, className = "" }: { children: ReactNode; className?: string }) {
  const { open } = useContext(WaitlistContext);
  return <button type="button" onClick={open} className={`inline-flex min-h-12 items-center justify-center gap-2 rounded-md bg-creaty-lime px-6 py-3 text-sm font-bold text-creaty-black shadow-[var(--shadow-cta)] transition duration-300 hover:-translate-y-0.5 hover:brightness-105 ${className}`}>{children}<ArrowRight className="h-4 w-4" /></button>;
}

function Logo({ compact = false }: { compact?: boolean }) {
  return <a href="#top" aria-label="Ir al inicio" className="inline-flex shrink-0 items-center"><img src={creatyLogo} alt="Creaty" className={`${compact ? "h-11 md:h-14" : "h-14 md:h-[72px]"} w-auto object-contain`} /></a>;
}

function Navbar() {
  const [scrolled, setScrolled] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  useEffect(() => {
    const update = () => setScrolled(window.scrollY > 80);
    update(); window.addEventListener("scroll", update, { passive: true });
    return () => window.removeEventListener("scroll", update);
  }, []);
  const links = [["Por qué Creaty", "#problema"], ["Cómo te ayuda", "#solucion"], ["Cómo funciona", "#como-funciona"], ["Por qué es diferente", "#diferencial"]];
  return <header className={`fixed inset-x-0 top-0 z-[100] border-b transition-all duration-300 ${scrolled || menuOpen ? "border-creaty-cream/10 bg-creaty-black/95 shadow-[var(--shadow-nav)] backdrop-blur-xl" : "border-transparent bg-transparent"}`}>
    <div className="mx-auto flex max-w-7xl items-center justify-between gap-3 px-4 py-2 md:px-8">
      <Logo compact />
      <nav className="hidden items-center gap-7 lg:flex">{links.map(([label, href]) => <a key={href} href={href} className="text-sm font-medium text-creaty-cream/65 transition hover:text-creaty-cream">{label}</a>)}</nav>
      <div className="ml-auto flex items-center gap-2"><CTAButton className="min-h-10 px-3 py-2 text-[11px] sm:px-4 sm:text-xs">Regístrate ahora</CTAButton><button type="button" aria-label={menuOpen ? "Cerrar menú" : "Abrir menú"} aria-expanded={menuOpen} onClick={() => setMenuOpen(v => !v)} className="grid h-10 w-10 place-items-center rounded-md border border-creaty-cream/15 text-creaty-cream lg:hidden">{menuOpen ? <X className="h-5 w-5" /> : <Menu className="h-5 w-5" />}</button></div>
    </div>
    {menuOpen && <nav className="border-t border-creaty-cream/10 bg-creaty-black px-5 py-4 lg:hidden">{links.map(([label, href]) => <a key={href} href={href} onClick={() => setMenuOpen(false)} className="block border-b border-creaty-cream/10 py-3 text-sm text-creaty-cream/80 last:border-0">{label}</a>)}</nav>}
  </header>;
}

const ventures = [
  ["AR", "Ana Rivera", "EdTech", "hace 2 días", "En progreso", "bg-creaty-purple"],
  ["DC", "Diego Castro", "HealthTech", "hace 5 días", "Bloqueo atención", "bg-creaty-orange"],
  ["SM", "Sara Morales", "AgroTech", "hace 1 día", "En progreso", "bg-creaty-lime"],
  ["JL", "Juan López", "EdTech", "hace 14 días", "En pausa", "bg-creaty-cream"],
  ["CT", "Camila Torres", "Marketplace", "hace 3 días", "En progreso", "bg-creaty-purple"],
  ["LV", "Laura Vélez", "Sustainability", "hace 4 días", "En progreso", "bg-creaty-orange"],
];
const stages = [["Idea y validación", 100], ["Validación de problema", 80], ["Pricing y modelo de negocio", 40], ["MVP y primeras ventas", 20], ["Tracción y escalamiento", 0]] as const;

function Avatar({ initials, tone = "bg-creaty-purple" }: { initials: string; tone?: string }) { return <span className={`grid h-8 w-8 shrink-0 place-items-center rounded-full ${tone} text-[10px] font-extrabold text-creaty-black`}>{initials}</span>; }
function SearchBox({ label }: { label: string }) { return <div className="flex items-center gap-2 rounded-md border border-creaty-black/10 bg-background px-3 py-2 text-[10px] text-creaty-black/40"><Search className="h-3.5 w-3.5" />{label}</div>; }

function DashboardMockup() {
  return <div className="relative mt-12 md:mt-16">
    <div className="mock-note -left-8 top-36">Lista de emprendimientos con estado y última actualización<span>↘</span></div>
    <div className="mock-note -right-8 top-28">Métricas clave de un vistazo<span>↙</span></div>
    <div className="mock-note -right-10 top-[52%]">Permite identificar rápidamente quién necesita tu atención<span>↙</span></div>
    <div className="mock-note -left-5 bottom-24">Próximos pasos más relevantes<span>↗</span></div>
    <div className="mock-note -right-5 bottom-36">Progreso visual del emprendimiento o del portafolio<span>↖</span></div>
    <div className="relative z-10 overflow-hidden rounded-lg border border-creaty-black/10 bg-background shadow-[var(--shadow-panel)]">
      <div className="flex h-14 items-center gap-3 border-b border-creaty-black/10 px-3 md:px-5"><span className="text-base font-black">Creaty<span className="text-creaty-orange">.</span></span><div className="ml-auto hidden w-48 sm:block"><SearchBox label="Buscar..." /></div><Bell className="h-4 w-4"/><Avatar initials="AP" tone="bg-creaty-lime" /></div>
      <div className="grid md:grid-cols-[150px_250px_1fr]">
        <aside className="hidden min-h-[720px] flex-col border-r border-creaty-black/10 p-3 md:flex">
          {[LayoutDashboard, Users, CalendarDays, ListChecks, FileText].map((Icon, i) => <div key={i} className={`mb-1 flex items-center gap-2 rounded-md px-3 py-2 text-[10px] font-semibold ${i === 0 ? "bg-creaty-lime/35" : "text-creaty-black/55"}`}><Icon className="h-3.5 w-3.5" />{["Inicio", "Mis emprendimientos", "Calendario", "Tareas", "Recursos"][i]}</div>)}
          <div className="mt-auto flex items-center gap-2 border-t border-creaty-black/10 pt-3"><Avatar initials="AP" tone="bg-creaty-purple"/><span className="text-[9px]"><b>Alejandro Pérez</b><br/>Mentor</span></div>
        </aside>
        <div className="border-r border-creaty-black/10 p-3 md:p-4"><div className="mb-3 text-xs font-bold">Mis emprendimientos (8)</div><SearchBox label="Buscar emprendimiento..."/><div className="mt-3 grid gap-2 sm:grid-cols-2 md:grid-cols-1">{ventures.map(([initials,name,sector,last,status,tone]) => <div key={name} className="flex min-w-0 items-center gap-2 rounded-md border border-creaty-black/8 p-2"><Avatar initials={initials} tone={tone}/><div className="min-w-0 flex-1"><div className="truncate text-[10px] font-bold">{name}</div><div className="text-[8px] text-creaty-black/50">{sector} · Últ. sesión: {last}</div></div><span className={`rounded-full px-1.5 py-1 text-[7px] font-bold ${status === "Bloqueo atención" ? "bg-danger-soft text-danger" : status === "En pausa" ? "bg-creaty-black/8 text-creaty-black/50" : "bg-success-soft text-success"}`}>{status}</span></div>)}</div></div>
        <main className="min-w-0 p-3 md:p-4">
          <div className="no-scrollbar -mx-3 flex gap-2 overflow-x-auto px-3 pb-2 md:mx-0 md:grid md:grid-cols-4 md:px-0">{[["Emprendimientos activos","8","↑2 vs. semana anterior"],["Sesiones esta semana","5","↑1 vs. semana anterior"],["Requieren atención","2","↓1 vs. semana anterior"],["Avance promedio","68%","↑12% vs. mes anterior"]].map(([l,v,d],i)=><div key={l} className="min-w-[145px] rounded-md border border-creaty-black/10 p-3"><div className="flex items-center justify-between text-[8px] text-creaty-black/50">{l}{i===2&&<AlertTriangle className="h-3 w-3 text-danger"/>}</div><div className="mt-1 text-xl font-black">{v}</div><div className={`text-[7px] ${i===2?"text-danger":"text-success"}`}>{d}</div></div>)}</div>
          <div className="mt-3 grid gap-3 lg:grid-cols-[1.15fr_.85fr]">
            <div className="rounded-md bg-creaty-black p-4 text-creaty-cream"><div className="text-[9px] uppercase text-creaty-lime">Tu próxima mentoría</div><div className="mt-1 text-[10px] font-semibold">Jueves, 10 de abril · 10:00 a. m.</div><div className="mt-3 flex items-center gap-2"><Avatar initials="AR"/><div className="text-[10px]"><b>Ana Rivera</b><br/><span className="text-creaty-cream/50">EdTech</span></div><button className="ml-auto rounded-md bg-creaty-lime px-2 py-1.5 text-[8px] font-bold text-creaty-black">Ver detalle →</button></div><div className="mt-4 text-[9px] font-bold">Resumen para tu sesión</div><p className="mt-1 text-[8px] leading-relaxed text-creaty-cream/65">Ha avanzado en la validación de problema. El pricing continúa pendiente. Ha entrevistado a 8 usuarios y validado la propuesta de valor.</p><div className="mt-3 rounded-md bg-creaty-purple/20 p-2 text-[8px]"><Sparkles className="mr-1 inline h-3 w-3 text-creaty-purple"/><b>Foco sugerido por IA:</b> Validar disposición a pagar y explorar modelos de pricing.</div></div>
            <div className="rounded-md border border-creaty-black/10 p-4"><div className="flex items-center justify-between text-[10px] font-bold">Avance por etapa <span className="rounded border px-2 py-1 text-[8px] font-normal">Todos</span></div><div className="mt-4 space-y-3">{stages.map(([label,p])=><div key={label}><div className="flex justify-between text-[8px]"><span>{label}</span><b>{p}%</b></div><div className="mt-1 h-1.5 rounded-full bg-creaty-black/8"><div className={`h-full rounded-full ${p===40?"bg-creaty-orange":"bg-progress"}`} style={{width:`${p}%`}}/></div></div>)}</div></div>
          </div>
          <div className="mt-3"><div className="mb-2 flex justify-between text-[10px] font-bold">Próximos pasos de tu portafolio <span className="text-[8px] font-medium">Ver todas las tareas →</span></div><div className="grid gap-2 sm:grid-cols-3">{[["Ana Rivera","Validar pricing","10 abr"],["Diego Castro","Entrevistas usuarios","12 abr"],["Sara Morales","Preparar pitch","13 abr"]].map(([n,t,d])=><div key={n} className="rounded-md border border-creaty-black/10 p-2 text-[8px]"><b>{n}</b><div className="mt-1 text-creaty-black/55">{t}</div><span className="mt-2 inline-block rounded bg-creaty-lime/45 px-1.5 py-0.5 font-bold">{d}</span></div>)}</div></div>
        </main>
      </div>
    </div>
    <div className="mt-5 flex flex-wrap gap-2 md:hidden">{["Lista y estado", "Atención prioritaria", "Métricas clave", "Progreso visual", "Próximos pasos"].map((x,i)=><span key={x} className="rounded-full border border-creaty-black/15 bg-background px-3 py-1.5 text-[10px] font-semibold">{i+1}. {x}</span>)}</div>
  </div>;
}

function Hero() {
  const reduce = useReducedMotion();
  return <section id="top" className="relative flex min-h-[780px] items-center overflow-hidden bg-creaty-black px-5 pb-24 pt-36 text-creaty-cream md:min-h-[860px] md:px-10 md:pt-44"><div className="hero-grid absolute inset-0 opacity-40"/><div className="absolute inset-x-0 bottom-0 h-px bg-gradient-to-r from-transparent via-creaty-lime/50 to-transparent"/><motion.div initial={reduce?false:{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.8}} className="relative mx-auto max-w-5xl text-center"><h1 className="text-balance text-[clamp(2.7rem,7vw,6.8rem)] font-black leading-[.98] tracking-normal">Más emprendimientos acompañados. <span className="text-creaty-lime">Menos tiempo</span> preparando cada mentoría.</h1><p className="mx-auto mt-7 max-w-3xl text-base leading-relaxed text-creaty-cream/70 md:text-xl">Creaty centraliza los avances de tus emprendedores y te ayuda a llegar a cada sesión con el contexto y los próximos pasos claros, para que dediques tu tiempo a aportar valor.</p><div className="mt-9 flex flex-col items-center"><CTAButton>Regístrate ahora</CTAButton><span className="mt-3 text-xs text-creaty-cream/45">Y recibe gratis un diagnóstico como mentor para iniciar</span></div></motion.div></section>;
}

function DashboardSection(){return <Section light><div className="mx-auto max-w-4xl text-center"><p className="text-xs font-bold uppercase text-creaty-orange">Un solo lugar para acompañar mejor</p><h2 className="mt-4 text-balance text-3xl font-black leading-tight md:text-5xl">Todo lo que necesitas saber antes de tu próxima mentoría.</h2><p className="mx-auto mt-5 max-w-2xl text-creaty-black/60">Avances, acuerdos, próximos pasos y recomendaciones de cada emprendimiento, organizados en un solo lugar.</p></div><h3 className="mx-auto mt-16 max-w-3xl text-center text-2xl font-extrabold md:text-4xl">Llega con contexto. Empieza aportando valor desde el primer minuto.</h3><DashboardMockup/></Section>}

const problems = [
["Llegas a la sesión sin recordar todo el contexto.","Antes de cada mentoría tienes que revisar conversaciones, avances y sesiones anteriores para volver a entender dónde está cada emprendimiento."],
["No sabes si avanzaron hasta que vuelves a verlos.","Entre una sesión y otra pierdes visibilidad sobre tareas, compromisos y bloqueos. Cuando algo se estanca, te enteras tarde."],
["No todos los emprendedores necesitan la misma mentoría.","Cada equipo está en un momento distinto, con retos y prioridades diferentes. Adaptar el acompañamiento a cada caso exige contexto y criterio."],
["Termina la mentoría, pero los próximos pasos no quedan claros y organizados.","En sesiones presenciales o virtuales, convertir lo conversado en tareas, responsables y próximos pasos claros termina siendo otro trabajo después de mentorear."],
];
function Problema(){return <Section id="problema"><div className="max-w-4xl"><p className="text-xs font-bold uppercase text-creaty-orange">Por qué Creaty</p><h2 className="mt-4 text-balance text-3xl font-black md:text-5xl">Tu tiempo debería estar dedicado a mentorear, no reconstruyendo lo que pasó.</h2><p className="mt-5 max-w-2xl text-creaty-cream/60">Entre una sesión y otra, el contexto se dispersa, los compromisos se enfrían y preparar cada caso vuelve a consumir tiempo.</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-lg border border-creaty-cream/10 bg-creaty-cream/10 md:grid-cols-2">{problems.map(([t,d],i)=><article key={t} className="bg-creaty-black p-6 md:p-8"><span className={`text-4xl font-black ${i%2?"text-creaty-purple":"text-creaty-orange"}`}>0{i+1}</span><h3 className="mt-5 text-lg font-bold">{t}</h3><p className="mt-3 text-sm leading-relaxed text-creaty-cream/55">{d}</p></article>)}</div><div className="mt-12 flex flex-col items-start justify-between gap-5 border-t border-creaty-cream/10 pt-8 md:flex-row md:items-center"><p className="max-w-xl font-semibold">Descubre qué puedes mejorar en tu forma de acompañar y recibe gratis tu diagnóstico como mentor.</p><CTAButton>Haz tu diagnóstico gratis</CTAButton></div></Section>}

const values = [
[LayersIcon,"Todo el contexto, en un solo lugar.","Avances, acuerdos y decisiones de cada emprendimiento, listos antes de tu próxima mentoría.","bg-creaty-lime"],
[ListChecks,"Seguimiento que continúa entre sesiones.","Mantén visibles los avances, compromisos y bloqueos sin esperar hasta la próxima mentoría.","bg-creaty-purple"],
[BrainCircuit,"Orientación para cada emprendimiento.","Creaty, a través de IA, conecta la etapa, los avances y las necesidades de cada equipo para ayudarte a identificar dónde enfocarte.","bg-creaty-orange"],
[MessageSquareText,"De la conversación a la acción.","Convierte lo trabajado en la sesión en tareas, responsables y próximos pasos claros para el equipo.","bg-creaty-black text-creaty-lime"],
] as const;
function LayersIcon(props:{className?:string}){return <LayoutDashboard {...props}/>}

const processStages = [["Idea y validación","100%"],["Validación de problema","100%"],["Propuesta de valor","80%"],["Pricing y modelo de negocio","En progreso · 40%"],["MVP y primeras ventas","20%"],["Tracción y escalamiento","0%"]];
function ProcessMap(){return <div className="relative mt-16"><div className="mock-note -left-8 top-16">Información general del emprendimiento<span>↘</span></div><div className="mock-note -right-8 top-36">Bloqueo identificado de forma clara<span>↙</span></div><div className="mock-note -right-5 bottom-16">Siguiente paso sugerido por IA<span>↖</span></div><div className="mock-note -left-5 bottom-10">Etapas del proceso con progreso claro<span>↗</span></div>
<div className="relative z-10 rounded-lg border border-creaty-black/10 bg-background p-4 shadow-[var(--shadow-panel)] md:p-7"><div className="flex flex-col gap-4 border-b border-creaty-black/10 pb-5 lg:flex-row lg:items-end"><div className="flex items-start gap-3"><ArrowLeft className="mt-1 h-4 w-4"/><div><h3 className="text-xl font-black">Ana Rivera</h3><p className="text-xs text-creaty-black/45">EdTech · Educación personalizada con IA</p></div></div><div className="no-scrollbar flex gap-5 overflow-x-auto lg:ml-auto">{["Resumen","Sesiones","Tareas","Documentos","Notas"].map((x,i)=><span key={x} className={`shrink-0 pb-2 text-[10px] font-semibold ${i===0?"border-b-4 border-creaty-lime":"text-creaty-black/45"}`}>{x}</span>)}</div></div>
<div className="mt-5 grid gap-3 lg:grid-cols-[1.35fr_.8fr_.8fr]"><div className="grid rounded-md border border-creaty-black/10 p-5 sm:grid-cols-[1fr_110px]"><div><p className="text-[10px] text-creaty-black/45">Etapa actual</p><h4 className="mt-2 text-lg font-black">Validación comercial</h4><p className="mt-2 text-xs leading-relaxed text-creaty-black/50">Está validando la disposición a pagar y explorando modelos de negocio.</p></div><div className="mt-4 border-creaty-black/10 sm:mt-0 sm:border-l sm:pl-5"><p className="text-[10px] text-creaty-black/45">Avance general</p><div className="mt-3 grid h-20 w-20 place-items-center rounded-full bg-[conic-gradient(var(--creaty-progress)_60%,var(--creaty-track)_0)]"><div className="grid h-14 w-14 place-items-center rounded-full bg-background text-lg font-black">60%</div></div></div></div><div className="rounded-md bg-danger-soft p-5 text-danger"><AlertTriangle className="h-5 w-5"/><h4 className="mt-3 text-sm font-bold">Bloqueo detectado</h4><p className="mt-2 text-[10px] leading-relaxed">Aún no ha validado la disposición a pagar con usuarios reales.</p></div><div className="rounded-md bg-lime-soft p-5"><Lightbulb className="h-5 w-5"/><h4 className="mt-3 text-sm font-bold">Próximo foco sugerido por IA</h4><p className="mt-2 text-[10px] leading-relaxed">Diseñar 3 hipótesis de pricing y validarlas con 5 clientes potenciales.</p></div></div>
<div className="mt-4 rounded-md border border-creaty-black/10 p-5"><p className="text-xs font-bold">Mapa de proceso</p><div className="process-stepper mt-6">{processStages.map(([name,status],i)=><div key={name} className="process-step"><span className={`process-number ${i<3?"done":i===3?"current":"future"}`}>{i+1}</span><div><div className="text-[9px] font-semibold leading-tight">{name}</div><div className={`mt-1 flex items-center gap-1 text-[8px] font-bold ${i===3?"text-creaty-orange":i<3?"text-success":"text-creaty-black/35"}`}>{i<3?<Check className="h-3 w-3"/>:<span className="h-2 w-2 rounded-full border currentColor"/>}{status}</div></div></div>)}</div></div></div>
<div className="mt-5 flex flex-wrap gap-2 md:hidden">{["Información general", "Etapas y progreso", "Bloqueo identificado", "Siguiente paso de IA"].map((x,i)=><span key={x} className="rounded-full border border-creaty-black/15 bg-background px-3 py-1.5 text-[10px] font-semibold">{i+1}. {x}</span>)}</div></div>}

function Solucion(){return <Section id="solucion" light><div className="mx-auto max-w-4xl text-center"><p className="text-xs font-bold uppercase text-creaty-orange">Todo lo que necesitas para un acompañamiento de verdad</p><h2 className="mt-4 text-balance text-3xl font-black md:text-5xl">Tu experiencia hace la mentoría. Creaty hace que llegues preparado.</h2><p className="mx-auto mt-5 max-w-3xl text-creaty-black/60">Con Creaty conectas lo que ocurrió, lo que avanzó y lo que debería seguir para que tú puedas concentrarte en preguntar, analizar y orientar a tus emprendedores.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{values.map(([Icon,t,d,c])=><article key={t} className="rounded-lg border border-creaty-black/10 bg-background p-5"><div className={`grid h-11 w-11 place-items-center rounded-md ${c}`}><Icon className="h-5 w-5"/></div><h3 className="mt-5 font-extrabold">{t}</h3><p className="mt-3 text-sm leading-relaxed text-creaty-black/55">{d}</p></article>)}</div><ProcessMap/></Section>}

function Como(){const steps=[["01","Prepárate","Entiende dónde está cada emprendimiento y qué necesita atención antes de comenzar."],["02","Acompaña","Captura lo importante de la sesión y convierte acuerdos en tareas, responsables y próximos pasos claros."],["03","Da continuidad","Haz seguimiento a los avances y llega a la siguiente sesión sabiendo qué cambió y dónde aportar."]];return <Section id="como-funciona"><p className="text-xs font-bold uppercase text-creaty-purple">Tres pasos. Una mentoría más inteligente.</p><h2 className="mt-4 max-w-4xl text-balance text-3xl font-black md:text-5xl">Antes. Durante. Después. Sin perder el hilo.</h2><div className="mt-12 grid gap-3 md:grid-cols-3">{steps.map(([n,t,d],i)=><article key={n} className="rounded-lg border border-creaty-cream/10 p-6"><span className={`text-6xl font-black ${i===1?"text-creaty-orange":"text-creaty-lime"}`}>{n}</span><h3 className="mt-8 text-xl font-bold">{t}</h3><p className="mt-3 text-sm leading-relaxed text-creaty-cream/55">{d}</p></article>)}</div><div className="mt-12 flex flex-col items-start justify-between gap-5 border-t border-creaty-cream/10 pt-8 md:flex-row md:items-center"><p className="max-w-xl font-semibold">Descubre cómo Creaty puede ayudarte a preparar, acompañar y dar seguimiento a tus emprendedores.</p><CTAButton>Haz tu diagnóstico gratis</CTAButton></div></Section>}

function Diferencial(){return <Section id="diferencial" light><p className="text-xs font-bold uppercase text-creaty-orange">No es solo gestión de tareas</p><h2 className="mt-4 max-w-5xl text-balance text-3xl font-black md:text-5xl">Tus herramientas guardan información. Creaty te ayuda a convertirla en una mejor mentoría.</h2><div className="mt-12 grid overflow-hidden rounded-lg border border-creaty-black/10 lg:grid-cols-2"><div className="bg-background p-6 md:p-9"><p className="text-xs font-bold uppercase text-creaty-black/40">Otras herramientas</p><div className="mt-7 space-y-3">{["Notion","Excel","CRM","Agenda de notas","Otros"].map(x=><div key={x} className="flex items-center gap-3 border-b border-creaty-black/8 pb-3 text-sm"><X className="h-4 w-4 text-creaty-orange"/>{x}</div>)}</div><p className="mt-8 text-lg font-bold">Tú organizas, interpretas y decides qué sigue.</p></div><div className="bg-creaty-black p-6 text-creaty-cream md:p-9"><p className="text-xs font-bold uppercase text-creaty-lime">Con Creaty</p><div className="mt-7 flex min-h-48 items-center"><p className="text-balance text-2xl font-black leading-snug md:text-4xl">Mantiene contexto, conecta avances y te ayuda a preparar el siguiente paso.</p></div><div className="mt-5 h-2 w-full rounded-full bg-creaty-cream/10"><div className="h-full w-4/5 rounded-full bg-creaty-lime"/></div></div></div></Section>}

function Credibility(){return <Section light className="!pt-8"><div className="rounded-lg bg-creaty-purple/25 px-6 py-14 md:px-12"><div className="grid gap-8 md:grid-cols-[auto_1fr] md:items-center"><div className="grid h-16 w-16 place-items-center rounded-full bg-creaty-purple"><Users className="h-7 w-7"/></div><div><p className="text-xs font-bold uppercase text-creaty-black/50">Diseñado junto a mentores empresariales</p><h2 className="mt-3 text-balance text-3xl font-black md:text-5xl">Construido con quienes saben lo que significa acompañar emprendedores.</h2><p className="mt-5 max-w-4xl text-creaty-black/60">Estamos desarrollando Creaty junto a mentores empresariales para convertir problemas reales de tu día a día en una herramienta que realmente ahorra tiempo y mejore tu acompañamiento.</p></div></div></div></Section>}

function FinalCTA(){return <Section><div className="mx-auto max-w-4xl text-center"><Target className="mx-auto h-10 w-10 text-creaty-orange"/><h2 className="mt-6 text-balance text-4xl font-black md:text-6xl">Tu siguiente mentoría empieza mucho antes de la sesión.</h2><p className="mx-auto mt-6 max-w-3xl text-creaty-cream/65">Regístrate, recibe gratis tu diagnóstico como mentor y sé de los primeros en conocer cómo Creaty puede ayudarte a acompañar más emprendimientos dedicando menos tiempo operativo a preparar cada sesión.</p><div className="mt-9"><CTAButton>Regístrate ahora</CTAButton></div></div></Section>}

const fieldClass="mt-2 min-h-11 w-full rounded-md border border-creaty-black/15 bg-background px-3 py-2 text-sm text-creaty-black outline-none transition focus:border-creaty-black focus:ring-2 focus:ring-creaty-lime";
function Field({label,name,type="text"}:{label:string;name:string;type?:string}){return <label className="block text-sm font-semibold">{label}<input className={fieldClass} name={name} type={type} required/></label>}
function SelectField({label,name,options}:{label:string;name:string;options:string[]}){return <label className="block text-sm font-semibold">{label}<select className={fieldClass} name={name} required defaultValue=""><option value="" disabled>Selecciona una opción</option>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function WaitlistForm({onSuccess}:{onSuccess:()=>void}){const [sending,setSending]=useState(false);async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setSending(true);const data=Object.fromEntries(new FormData(e.currentTarget));const {error}=await supabase.from("mentor_waitlist").insert({name:String(data.name),email:String(data.email),phone:String(data.phone),simultaneous_ventures:String(data.simultaneous_ventures),mentorship_mode:String(data.mentorship_mode),professional_role:String(data.professional_role)});setSending(false);if(error){toast.error("No pudimos completar tu registro. Inténtalo de nuevo.");return}toast.success("Gracias por registrarte. Pronto recibirás noticias de Creaty.");onSuccess()}
return <form onSubmit={submit} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Nombre" name="name"/><Field label="Correo" name="email" type="email"/><Field label="Celular" name="phone" type="tel"/><SelectField label="¿Cuántos emprendimientos acompañas usualmente en simultáneo?" name="simultaneous_ventures" options={["1-5","6-10","11-15","Más de 15"]}/></div><SelectField label="¿Cómo realizas principalmente tus mentorías?" name="mentorship_mode" options={["Por cuenta propia","A través de una incubadora, aceleradora o programa","Como parte de una red de mentores","Desde una empresa de consultoría o mentoría","Otro"]}/><SelectField label="¿Qué lugar ocupa la mentoría en tu actividad profesional?" name="professional_role" options={["Es mi actividad principal","Es una actividad complementaria frecuente","Mentoreo ocasionalmente"]}/><button disabled={sending} type="submit" className="flex min-h-12 w-full items-center justify-center rounded-md bg-creaty-lime px-5 font-bold text-creaty-black transition hover:brightness-105 disabled:opacity-60">{sending?"Enviando...":"Quiero mi diagnóstico gratis"}</button></form>}
function WaitlistModal({open,onClose}:{open:boolean;onClose:()=>void}){useEffect(()=>{if(!open)return;const key=(e:KeyboardEvent)=>e.key==="Escape"&&onClose();document.addEventListener("keydown",key);document.body.style.overflow="hidden";return()=>{document.removeEventListener("keydown",key);document.body.style.overflow=""}},[open,onClose]);if(!open)return null;return <div role="dialog" aria-modal="true" aria-labelledby="modal-title" onMouseDown={e=>e.target===e.currentTarget&&onClose()} className="fixed inset-0 z-[200] grid place-items-center bg-creaty-black/85 p-3 backdrop-blur-sm"><div className="relative max-h-[94vh] w-full max-w-2xl overflow-y-auto rounded-lg bg-creaty-cream p-5 text-creaty-black shadow-[var(--shadow-modal)] md:p-8"><button type="button" onClick={onClose} aria-label="Cerrar formulario" className="absolute right-4 top-4 grid h-9 w-9 place-items-center rounded-full border border-creaty-black/15"><X className="h-5 w-5"/></button><p className="text-xs font-bold uppercase text-creaty-orange">Creaty para mentores</p><h2 id="modal-title" className="mt-3 pr-12 text-2xl font-black md:text-4xl">Empieza conociendo cómo mentoreas.</h2><p className="mb-7 mt-3 text-sm leading-relaxed text-creaty-black/60">Regístrate para ser de los primeros en probar Creaty y recibe gratis un diagnóstico de tu perfil como mentor.</p><WaitlistForm onSuccess={onClose}/></div></div>}
function Footer(){return <footer className="border-t border-creaty-cream/10 bg-creaty-black px-5 py-8 text-creaty-cream"><div className="mx-auto flex max-w-7xl flex-col items-center justify-between gap-4 sm:flex-row"><Logo compact/><span className="text-xs text-creaty-cream/40">© 2026 Creaty. Mentorías con más contexto.</span></div></footer>}

export default function Landing(){const [open,setOpen]=useState(false);return <WaitlistContext.Provider value={{open:()=>setOpen(true)}}><Navbar/><main><Hero/><DashboardSection/><Problema/><Solucion/><Como/><Diferencial/><Credibility/><FinalCTA/></main><Footer/><WaitlistModal open={open} onClose={()=>setOpen(false)}/></WaitlistContext.Provider>}
